### ISSUE TITLE
Rendre le site indexable par Google

### ISSUE THREAD

**Issue by j15e** [webaquebec/webaquebec2016-web#12]
À ma connaissance il faudrait utiliser le push state pour que Google indexe des pages (les urls avec bang # il faut utiliser la méthode de rendu backend ?_escaped_fragment_ qui est compliqué et deprecated anyway).

https://googlewebmastercentral.blogspot.ca/2015/10/deprecating-our-ajax-crawling-scheme.html

**Comment by cotlod** [comment]
On va utiliser web-selenium headless driver pour faire un render indexable du site. Je suis deja entrain de setupper le script!

Cheers!

**Comment by j15e** [comment]
Ok, vous allez faire le setup directement sur le serveur de production? Vous avez les accès je crois?

**Comment by cotlod** [comment]
Je viens de faire le PR, resterait juste a rouler le sh comme expliqué quand vous allez avoir fini vos modifications!

Cheers!

**Comment by j15e** [comment]
Réglé avec les dernières PR.
