### ISSUE TITLE
Overlap pour les titres trop longs sur les conférences

### ISSUE THREAD

**Issue by jasonlemay** [webaquebec/webaquebec2016-web#14]
![image](https://cloud.githubusercontent.com/assets/2584073/12430881/33f4eefa-bec0-11e5-9418-5d450db4ccd8.png)

Semble être rapidement fixable avec de l'ajout de padding sur l'élément `conference-header`

![image](https://cloud.githubusercontent.com/assets/2584073/12430851/09cc73f0-bec0-11e5-8f66-28e46a6e540d.png)

**Comment by j15e** [comment]
Pas réglé. Serait pas du à régler d'après moi aussi.

**Comment by j15e** [comment]
Corrigé (je sais pas dans quel commit exactement sorry)
