### ISSUE TITLE
Styles for links & bold text missing

### ISSUE THREAD

**Issue by j15e** [webaquebec/webaquebec2016-web#15]
On a pas mis de liens dans les articles encore mais il n'y a pas de style pour les liens. 

Faudrait mettre un gris/noir ou quelque chose en tout cas!

![capture d ecran 2016-01-20 a 10 57 17](https://cloud.githubusercontent.com/assets/143380/12454247/a746b682-bf64-11e5-9f34-9efbe3eb854f.png)

**Comment by paulcote** [comment]
Il n'y a pas de styles pour les strong non plus. Il s'affiche comme du texte normal.

**Comment by cotlod** [comment]
fixed in the latest PR

https://github.com/webaquebec/webaquebec2016-web/pull/40

**Comment by j15e** [comment]
Il manque bold <b> aussi

**Comment by j15e** [comment]
En particulier [cet article là](http://webaquebec.org/#!devenir-benevole-web-a-quebec-2016) est mal affiché. Je vais changer les b pour des strong pour là mais faudrait corriger la stylesheet.
