### ISSUE TITLE
Très petit texte + user-scalable=no

### ISSUE THREAD

**Issue by L-A** [webaquebec/webaquebec2016-web#18]
`content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"` tout ensemble, ça barre le chemin aux gens qui ont besoin de lire le texte en plus grand que les 10-11px qui apparaissent dans le site. La solution simple serait de simplement retirer `maximum-scale` et `user-scalable=no`. Je le signale parce que les réglages de scaling sont souvent inclus par des boilerplates.

**Comment by jasonlemay** [comment]
+1

**Comment by j15e** [comment]
Je crois que c'est nécessaire pour que les actions de swipe fonctionne.

**Comment by j15e** [comment]
AKA vaudrait mieux grossier les trucs trop petits sur mobile ou remplacer/annuler entièrement la navigation par swipe (ce qui serait quand même plate vu l'énergie mis dans ça bien que c'est pas parfait).

**Comment by j15e** [comment]
*Mais j'ai pas testé peut-être que c'est compatible, mais ça serait logique que non.

**Comment by L-A** [comment]
Ça serait difficile qu'une navigation par swipe soit déclenchée par les événement "panning" d'un viewport zoomé. Sinon ça voudrait dire que tout repose sur un hijack complet des événements touch (genre le scrolling est jamais naturel).

Démo sans `maximum-scale=1, user-scalable=no` trop rapide pour être du bon QA:

![zoomed-in](https://cloud.githubusercontent.com/assets/861964/12602447/662948fa-c477-11e5-92f3-379b2a4d4dde.gif)
