### ISSUE TITLE
Tickets page footer is broken

### ISSUE THREAD

**Issue by j15e** [webaquebec/webaquebec2016-web#2]
Je ne sais pas si quelqu'un travaille déjà à ajuster cette page (cc @cotlod peut-être?) mais pour être certain je le note ici, le pied de page de la section tickets ne permet pas de voir tout le contenu qu'on devrait voir. Ça semble avoir été brisé par le commit 293d7809f67fd466a033d4d3d58b2b143cb4773d.

J'ai mis à jour le contenu prévu avec c170fc99b9f021bb2514e773fae39be510dd6885

![capture d ecran 2016-01-17 a 18 59 53](https://cloud.githubusercontent.com/assets/143380/12380925/8f401f34-bd4c-11e5-9b27-b711b9041442.png)

**Comment by cotlod** [comment]
C'est fixed! Mais dans notre repo, je suis pas sur que c'est une bonne idée d'en avoir 2 présentement. :/

**Comment by j15e** [comment]
Ok good pour le fix. 

Il faudrait converger sur celui-ci, pouvez-vous faire ça? On peut ajouter des accès push s'il en manque. 

En principe toutes mes modifications ne touche que des ajustements au contenu et celles de Paul concerne le déploiement : il ne devrait donc pas y avoir de conflits complexes avec vos correctifs.

C'est le repo que @paulcote a configuré pour déployer sur notre serveur de production et on souhaite que le source du site soit public sur Github comme les années précédentes.

**Comment by j15e** [comment]
J'ai essayé vous pouvez merge votre branche `sprint4-bugfixes` dans master il n'y a pas de conflits.

Ceci dit ce bogue ne semble pas réglé (ou peut-être c'est sur une autre branche/repo auquel j'ai pas accès ou c'est juste pas push yet?)

**Comment by cotlod** [comment]
fixed, faut juste recompiler les assets pour voir les modifs, version up-to-date sur waq.cortex.ninja

**Comment by j15e** [comment]
Je le roule en local avec le watch, c'est effectivement corrigé maintenant, merci!
