### ISSUE TITLE
Description des conférenciers coupée

### ISSUE THREAD

**Issue by j15e** [webaquebec/webaquebec2016-web#23]
Il y a plusieurs conférences dont leur description est tronquée (je sais pas si on avait une consigne de taille limite de texte?)

![image](https://cloud.githubusercontent.com/assets/143380/12554113/f9dfad44-c348-11e5-919d-e8ade1e3f87a.png)

**Comment by paulcote** [comment]
Oui et non, mais le texte devrait pas cropper comme ça de toute façon.

**Comment by j15e** [comment]
Je confirme que c'est réglé, mais ça prend 2-3 refresh sur mobile parce que les assets sont pas versionné (le JS l'est maintenant #29 mais pas le CSS).

**Comment by mrheaumecortex** [comment]
@j15e I've opened Issue https://github.com/webaquebec/webaquebec2016-web/issues/33 for the css / caching issues. Not sure where we want to alter it there's 2 way to do it. I've left comments where to begin with if it ever helps those who maintain it.

Cheers.
