### ISSUE TITLE
Données chargés en double

### ISSUE THREAD

**Issue by j15e** [webaquebec/webaquebec2016-web#28]
Je n'ai pas réussi à reproduire, problème rapporté par @blirette

![slack for ios upload png](https://cloud.githubusercontent.com/assets/143380/12587603/18c4903c-c423-11e5-9456-395b615a22d1.jpeg)

**Comment by j15e** [comment]
J'ai vu des blog posts en double ce matin. Il y a bien un problème aléatoire avec le load des données.

**Comment by j15e** [comment]
<img width="1060" alt="capture d ecran 2016-02-18 a 10 46 13" src="https://cloud.githubusercontent.com/assets/143380/13148798/dd88ed12-d62c-11e5-83b3-612b4fae9919.png">

**Comment by cotlod** [comment]
Ca doit venir d'un event qui n'est pas cleané, je vais refaire une passe pour m'assurer que rien stick en memoire.

**Comment by j15e** [comment]
Ok si vous pouvez corriger ça ce serait bien, j'ai eu d'autres commentaires, ça arrive plus souvent que je pensais.

<img width="628" alt="capture d ecran 2016-02-21 a 21 38 16" src="https://cloud.githubusercontent.com/assets/143380/13208082/75aee764-d8e3-11e5-8030-297fe9ff809b.png">

**Comment by j15e** [comment]
Aussi je viens de remarquer que quand les données sont en double, on ne peut pas naviguer des les posts, ça fait une erreur `Uncaught TypeError: Cannot read property 'innerHTML' of null`.

```
Templating.load @   app_e2657236636ad7058c59.bundle.js:6653
Templating.Render   @   app_e2657236636ad7058c59.bundle.js:6642
AbstractView.RenderTemplate @   app_e2657236636ad7058c59.bundle.js:5755
BlogController.OnPostTemplateLoaded @   app_e2657236636ad7058c59.bundle.js:1098
EventGroup.FireEvent    @   app_e2657236636ad7058c59.bundle.js:456
EventDispatcher.DispatchEvent   @   app_e2657236636ad7058c59.bundle.js:407
AbstractView.OnTemplateLoaded   @   app_e2657236636ad7058c59.bundle.js:5786
(anonymous function)    @   app_e2657236636ad7058c59.bundle.js:5741
(anonymous function)    @   app_e2657236636ad7058c59.bundle.js:6245
_resolved   @   app_e2657236636ad7058c59.bundle.js:6268
DeferredI.resolve   @   app_e2657236636ad7058c59.bundle.js:6293
xhr.onload  @   app_e2657236636ad7058c59.bundle.js:5931
```

**Comment by j15e** [comment]
En fait je pense le problème c'est que le Main et le HomeController load les données du blog.

https://github.com/webaquebec/webaquebec2016-web/blob/master/src/com/cortex/waq/home/HomeController.ts#L57
https://github.com/webaquebec/webaquebec2016-web/blob/master/src/com/cortex/waq/main/Main.ts#L200

**Comment by j15e** [comment]
Je n'ai pas réussi à reproduire moi-même mais j'ai encore eu un rapport d'une personne qui voit l'horaire chargé en double aussi :

![capture d ecran 2016-02-24 a 13 42 29](https://cloud.githubusercontent.com/assets/143380/13296646/82ec8e2a-dafc-11e5-8272-eb968b3dec4f.png)

**Comment by cotlod** [comment]
Should be fixed in latest PR

https://github.com/webaquebec/webaquebec2016-web/pull/44

**Comment by j15e** [comment]
Pour le blogue c'est bien réglé, pour l'horaire je n'ai jamais réussi à reproduire alors on va fermer le bogue pour là à moins que vous avez une idée de pourquoi l'horaire pourrait charger en double de fois?

**Comment by jdecaron** [comment]
Le bug est plus difficile à reproduire pour l'horaire mais le principe est le même. Je vais faire une patch pour cette section aussi.
