### ISSUE TITLE
Setup Google Analytics

### ISSUE THREAD

**Issue by j15e** [webaquebec/webaquebec2016-web#3]
- [x] Set GID `UA-20043510-1`  
- [x] Setup auto-linker to EventBrite to track sales conversions `ga('linker:autoLink', ['www.eventbrite.com'] )`
- [x] Track pages & titles

**Comment by j15e** [comment]
@cotlod est-ce que vous avez une méthode standard pour recevoir les changements de page dans le site? est-ce que vous avez une sorte de routeur? un endroit ou je pourrais faire genre :

``` js
someEventHook(urlHash:string):void {
 ga('pageview', 'pageview', { 'page': urlHash, 'title': document.title })
}
```

**Comment by j15e** [comment]
Hum laisse faire en fait j'ai juste à utiliser `window.onhashchange`

**Comment by cotlod** [comment]
Yes dans le Main.ts c'est la que la navigation est setupped through Router.ts!

**Comment by j15e** [comment]
Je viens de voir qu'on a toujours pas de tracking correct des pages consultés si quelqu'un a le goût d'implanter ça.

![capture d ecran 2016-02-24 a 13 45 32](https://cloud.githubusercontent.com/assets/143380/13296726/ec1f5724-dafc-11e5-9b85-f6e8c6e81cff.png)
