### ISSUE TITLE
Problème de partage des articles / pages

### ISSUE THREAD

**Issue by j15e** [webaquebec/webaquebec2016-web#41]
Les bénévoles qui travaillent sur le blogue m'on fait part qu'avec Facebook on a des problèmes quand on veut partager un article ou une page du site.

On dirait que Facebook apprécie du tout pas les urls avec les hashbanh (il veut rien charger même pas la page de base).

La solution à mon avis serait d'utiliser le URL push state plutôt que les hash bang et pouvoir renvoyer à Facebook aussi une version pré-rendu de la page avec les bons métas.

<img width="1031" alt="capture d ecran 2016-02-21 a 22 49 06" src="https://cloud.githubusercontent.com/assets/143380/13209733/66cb8a7e-d8f5-11e5-84ce-96fbc250fc1a.png">

<img width="689" alt="capture d ecran 2016-02-21 a 23 44 09" src="https://cloud.githubusercontent.com/assets/143380/13209721/401be1b2-d8f5-11e5-872e-8295a4aeaab4.png">

**Comment by cotlod** [comment]
Salut JP,

Ca va etre fixed avec mon latest code review et un rerender des snapshots :)

https://github.com/webaquebec/webaquebec2016-web/pull/44

**Comment by j15e** [comment]
Fixed

![capture d ecran 2016-02-25 a 12 39 16](https://cloud.githubusercontent.com/assets/143380/13328467/cf9be624-dbbc-11e5-83ec-85ee5493f0ef.png)

**Comment by j15e** [comment]
Je confirme que ça fonctionne aussi pour les conférences, les conférenciers, bénévoles et partenaires. :100:

**Comment by cotlod** [comment]
:+1:
