### ISSUE TITLE
Missing style for list items on blogpost

### ISSUE THREAD

**Issue by jasonlemay** [webaquebec/webaquebec2016-web#42]
![image](https://cloud.githubusercontent.com/assets/2584073/13238968/d4956ebc-d9a4-11e5-8815-fcfe95c807f1.png)

**Comment by j15e** [comment]
Good catch! ref #15 il manque le `<b>` aussi.

**Comment by cotlod** [comment]
On it, will be fixed later

**Comment by jdecaron** [comment]
Le fix s'en vient sauf qu'il y a une double encapsulation de la dernière liste.

**Comment by j15e** [comment]
C'est corrigé pour le double `<ul>`

**Comment by jdecaron** [comment]
J'ai aussi ajouté le support de l'élément i, ça devrait arriver  sur le prochain push. Désolé de la confusion, j'ai assumé que i et b était déprécié mais il semblerait que le W3C l'a ramené en standard depuis HTML5.

**Comment by j15e** [comment]
Fixed by #50
