### ISSUE TITLE
Dernier article -> html truncate issue

### ISSUE THREAD

**Issue by j15e** [webaquebec/webaquebec2016-web#46]
faudrait prendre le data `except.rendered` et/ou truncate le texte en enlevant les tag html

![capture d ecran 2016-02-25 a 11 28 53](https://cloud.githubusercontent.com/assets/143380/13326216/fc47997a-dbb2-11e5-97d1-85e512a55905.png)

**Comment by j15e** [comment]
https://github.com/webaquebec/webaquebec2016-web/blob/master/src/com/cortex/waq/home/HomeController.ts#L89

Il faudrait faire quelque chose comme 

``` js
 $(this.mLatestBlog.text).text().substring(0, this.mBlogPostMaximumLength) + " ...";
```

**Comment by cotlod** [comment]
will be fixed dans la prochain PR :D
