### ISSUE TITLE
Sponsors images too large

### ISSUE THREAD

**Issue by j15e** [webaquebec/webaquebec2016-web#5]
Pour le concern de load des images trop grosses, vous avez accès dans l'API à un autre format que l'image originale qui je crois réglerait le problème.

Soit que ici : https://github.com/webaquebec/webaquebec2016-web/blob/master/src/com/cortex/waq/profiles/data/Profile.ts#L98

``` js
this.mThumbnail = !customFields.image_thumbnail ? "" : customFields.image_thumbnail.url;
# replace by ... 
this.mThumbnail = !customFields.image_thumbnail ? "" : customFields.image_thumbnail.sizes.medium;
```

![capture d ecran 2016-01-18 a 12 09 58](https://cloud.githubusercontent.com/assets/143380/12397708/f73b515e-bddc-11e5-87dd-9562d3bdd406.png)

cc @cotlod

**Comment by cotlod** [comment]
Le problème vient du fait que l'object profile est utilisé pour Speakers, Volunteers et Sponsors. Mettre du code custom au lieux de mettre les bonnes images dans le CMS, c'est pas top!

Cheers!

**Comment by j15e** [comment]
L'attribute `sizes.medium` existe pour tous les modèles alors ça ne causerait pas de problème de changer. 

L'histoire c'est que le champ média dans Wordpress s'appelle `image_thumbnail`, mais si tu prends direct l'url c'est la source originale, pas le thumb. Les urls des thumbs sont juste dans sizes.

Je ne suis pas un fan de Wordpress non plus sauf que l'avantage du CMS est justement que les bénévoles responsables des contenus peuvent uploader un peu n'importe quoi comme format et le CMS resize à un format raisonnable.
