### ISSUE TITLE
Impossible d'ouvrir les liens dans les articles de blogues

### ISSUE THREAD

**Issue by j15e** [webaquebec/webaquebec2016-web#54]
Il y a des liens sur les images et on ne peut pas cliquer :

http://webaquebec.org/#!5-excellents-themes-wordpress-a-effet-parallaxe

> J’ai viens de voir un autre dysfonctionnement, quand je mets un lien sur une image, celui-ci n’est pas pris en compte. 

Il y a aussi un problème qui fait que la mise en page proposé dans Wordpress ne s'applique pas réellement / correctement pour les images :

> Moins génant mais je le soulève quand même la mise en page des images n’est pas non plus gérée. si veux centrer ou mettre à gauche…

**Comment by j15e** [comment]
On m'a donné l'indice suivant : 

>  pointer-events à none dans le css pour toutes les images

**Comment by david-alex-cohen-zone** [comment]
Les images ont déjà cette propriété, je pencherai plutôt pour un problème sur 'display' pour les liens sur les images, ils sont actuellement inline (et prennent donc la taille d'une ligne en bas de l'image). 
Il faut trouver un selecteur pour les liens contenant des images et définir la propriété display à inline-block (pas 'block' sinon on risque d'impacter les images qui se suivent horizontalement)

Quelque chose comme ça par exemple :
`a[rel*='attachment'] {
    display: inline-block;
}`

**Comment by paulcote** [comment]
Non en fait c'est justement le pointer-events qui est à none qui empêche le fonctionnement du lien. Dès que le pointer-events est à auto pour les images de l'article, les liens fonctionnent.

**Comment by david-alex-cohen-zone** [comment]
Ha ok, autant pour moi :)
Par contre j'imagine que cette propriété doit être là pour une raison, il faudra voir les impacts sur le reste du site si on la retire

**Comment by paulcote** [comment]
En fait le pointer-events, de ce que j'ai pu comprendre, est là pour empêche le drag d'une image pour pouvoir faire le changement de page avec la gesture. Donc à la limite on pourrais juste mettre le pointer-events à auto pour les images à l'intérieur d'un lien.

**Comment by j15e** [comment]
Réglé, mais comme les assets ne sont pas fingerprinted ( #33 ) il faut reload complètement votre cache.
