### ISSUE TITLE
Images trop large sur blogue mobile

### ISSUE THREAD

**Issue by j15e** [webaquebec/webaquebec2016-web#56]
Ça prendrait un genre de max-width 100% sur les images dans le blogue.

![capture d ecran 2016-03-08 a 14 16 26](https://cloud.githubusercontent.com/assets/143380/13613040/5c26468c-e538-11e5-8ddb-dc6f00e3d06e.png)

**Comment by paulcote** [comment]
Pas juste sur mobile, ça fait sur desktop quand l'image est trop grosse aussi.

**Comment by jdecaron** [comment]
https://github.com/webaquebec/webaquebec2016-web/commit/830da4c5dfb30c44d048a9490efa246e4cbe3d7a

**Comment by jdecaron** [comment]
J'ai fait un commit au lieux d'un pull request par accident.
