### ISSUE TITLE
Hauteur des lignes de titres sur le blogue trop grande

### ISSUE THREAD

**Issue by j15e** [webaquebec/webaquebec2016-web#57]
Voir cet exemple :

![capture d ecran 2016-03-08 a 14 17 24](https://cloud.githubusercontent.com/assets/143380/13613069/7d7c70cc-e538-11e5-9e93-13edeacb97a9.png)

http://webaquebec.org/#!les-tendances-seo-2016-selon-ovh

**Comment by jdecaron** [comment]
https://github.com/webaquebec/webaquebec2016-web/pull/100
