### ISSUE TITLE
Contrast is too low (yellow on gray)

### ISSUE THREAD

**Issue by jasonlemay** [webaquebec/webaquebec2016-web#6]
![image](https://cloud.githubusercontent.com/assets/2584073/12398536/5243c78e-bde2-11e5-8fe7-78895223cb17.png)

**Comment by j15e** [comment]
On va répertorier une liste et on révisera avec Tristan. 

Il y a aussi les pauses qui sont limite

![capture d ecran 2016-01-18 a 13 35 03](https://cloud.githubusercontent.com/assets/143380/12399479/4d3e17de-bde8-11e5-9d83-078870d8e635.png)

**Comment by j15e** [comment]
Pour les plages horaire :

> Le mieux aurait été de mettre une pastille de couleur à côté au lieu que le libellé soit de couleur.

**Comment by j15e** [comment]
*Il y a déjà cette dite pastille

**Comment by jasonlemay** [comment]
Toujours utile : https://www.paciellogroup.com/resources/contrastanalyser/

**Comment by marjoriedoucet** [comment]
Toujours utile : http://jxnblk.com/colorable/demos/text/?foreground=%23757575&background=%23FFFFFF ;)
