### ISSUE TITLE
Zone cliquable trop large sur nom du conférencier

### ISSUE THREAD

**Issue by j15e** [webaquebec/webaquebec2016-web#62]
Le problème est le même sur dekstop mais cette capture mobile illustre bien la problématique ;

L'utilisateur veut généralement ouvrir la description de la conférence en cliquant dans la zone gris ou sur la photo mais il y a une bande de 100% de largeur qui fait un clic vers la fiche du conférencier.

![img_1455](https://cloud.githubusercontent.com/assets/143380/13623855/90fdcaa8-e577-11e5-93c7-14fb5688b8a0.PNG)

**Comment by jdecaron** [comment]
https://github.com/webaquebec/webaquebec2016-web/pull/74
