### ISSUE TITLE
Smooth scrooling vertical iOS bloqué?

### ISSUE THREAD

**Issue by j15e** [webaquebec/webaquebec2016-web#64]
Je ne sais pas si c'est moi qui imagine ça, mais j'ai l'impression que le scrolling vertical est "saccadé" ou "sec" sur mobile? Quelqu'un a une idée pourquoi?

**Comment by jdecaron** [comment]
Je confirme que c'est le cas sur iOS.

**Comment by j15e** [comment]
Allez-vous regarder pour le régler car c'est un des commentaires qui revient souvent? Ça donne l'impression que ça lag sur mobile (même si en réalité c'est pas un lag mais un comportement du scroll)

**Comment by jdecaron** [comment]
Je vais y travailler aujourd'hui.

**Comment by jdecaron** [comment]
J'ai trouvé la source du problème: nos éléments div n'avaient pas la propriété CSS -webkit-overflow-scrolling: touch;

Je vais ajouter cette propriété partout où on utilise des  div avec la propriété d'overflow: scroll.

Ensuite je vais synchroniser nos 2 repos. Car en ce moment on travaille encore sur GitLab et ça fait comme si on travaillait constamment sur 2 branches différentes. Et aussi vous n'êtes pas en mesure de voir nos changements quotidiens. C'est pas l'idéal d'avoir 2 repos différentes du même projet.

**Comment by jdecaron** [comment]
https://github.com/webaquebec/webaquebec2016-web/pull/77

**Comment by j15e** [comment]
> C'est pas l'idéal d'avoir 2 repos différentes du même projet.

À qui le dis-tu! Vous devriez travailler directement sur la version Github juste pas directement sur master.
