### ISSUE TITLE
Fiches profiles difficiles à consulter

### ISSUE THREAD

**Issue by j15e** [webaquebec/webaquebec2016-web#65]
Les fiches de conférenciers, de bénévoles et de partenaires sont assez difficiles à consulter sur mobile.

Il y a quelques trucs qu'on pourrait améliorer :
- [x] Réduire le line-height trop grand, augmenter un peu la taille de la police
- [x] Réduire un peu le ratio photo / texte ?
- [x] Rendre la fiche scrollable incluant la photo, pas seulement la partie du bas (idéal)

![img_1458](https://cloud.githubusercontent.com/assets/143380/13624378/88fc9dee-e57b-11e5-8ca4-a9a3e8547da3.PNG)

**Comment by j15e** [comment]
Note : c'est l'un des problèmes qui revient le plus souvent dans les commentaires (avec le scroll #64)

**Comment by jdecaron** [comment]
Je vais voir ce que je peux faire pour le scroll, on m'indique qu'on s'est déjà penché sur ce problème avant. Il se peut que j'arrive avec une meilleure solution.

**Comment by jdecaron** [comment]
https://github.com/webaquebec/webaquebec2016-web/pull/76
