### ISSUE TITLE
Menu de filtres n'apparait pas toujours

### ISSUE THREAD

**Issue by j15e** [webaquebec/webaquebec2016-web#66]
Je n'ai pas les étapes ou la situation précise pour reproduire à coup sur, mais il arrive que le menu de filtre de la programmation ne s'affiche pas (problème rapporté sur safari et chrome ios)

<img width="841" alt="capture d ecran 2016-03-09 a 10 22 45" src="https://cloud.githubusercontent.com/assets/143380/13639933/ef16151e-e5e0-11e5-9ddb-59b9550bd353.png">

**Comment by jdecaron** [comment]
Les étapes de reproduction pour ce bug sont les suivantes: avoir un appareil sur iOS 7 (peut être 8), s'assurer qu'il y ai eu une transition d'animation pour le menu des conférences, et ensuite cliquer sur les options (filtres). J'ai réglé ce problème, la patch arrivera sous peu.

**Comment by jdecaron** [comment]
https://github.com/webaquebec/webaquebec2016-web/pull/72
