### ISSUE TITLE
La navigation des journées de l'horaire devrait remonter en haut

### ISSUE THREAD

**Issue by j15e** [webaquebec/webaquebec2016-web#68]
On devrait remonter en haut (scroll top) quand on change de journée, ça fait comme pas de sens de garder la même position que la journée précédente.

**Comment by j15e** [comment]
*En fait, si toutes les journées étaient exactement identiques, ça serait moins problématique, mais parce qu'il y a une track de moins le mercredi à cause du Pixel Challenge et qu'il y a quelques trous on arrive pas au même endroit.

**Comment by jdecaron** [comment]
https://github.com/webaquebec/webaquebec2016-web/pull/73
