### ISSUE TITLE
Respecter les sauts des ligne des descriptions

### ISSUE THREAD

**Issue by j15e** [webaquebec/webaquebec2016-web#70]
Ce problème s'applique à plusieurs endroits, en fait tous les champs des description (conférences, conférenciers, partenaires, bénévoles, etc)

Dans l'admin : 

<img width="808" alt="capture d ecran 2016-03-10 a 10 38 50" src="https://cloud.githubusercontent.com/assets/143380/13674645/51a45fbc-e6ac-11e5-8406-dc26cb281d93.png">

Dans le site web, il faudrait convertir les sauts de ligne en BR pour garder un minimum de mise en forme :

<img width="612" alt="capture d ecran 2016-03-10 a 10 38 54" src="https://cloud.githubusercontent.com/assets/143380/13674662/5d20c916-e6ac-11e5-97e9-8d04eecdc60e.png">

http://webaquebec.org/#!robert-scoble

@paulcote sais-tu pourquoi il avait été décidé de prendre le champs description du custom field plutôt que le champs formaté du post? On fera pas le switch inverse rendu où on est, mais on s'entend que dans plusieurs cas l'idéal ça aurait été de pouvoir utiliser le post et avoir aussi accès à mettre des liens dans le texte, du bold, italique, etc...

**Comment by paulcote** [comment]
En gros, le plugin de schedule ajoutait des infos non voulues qui se retrouvait dans la description lorsque callé avec l'API de Wordpress. Je pourrais mettre un WYSIWYG pour la description custom par contre j'ai trop peur des impacts. Donc on va garder le status quo côté backend pour le moment c'est moins risqué.

**Comment by j15e** [comment]
Ok je comprends. Reste que faire des `<br>` pour les sauf de lignes ça serait déjà mieux!

**Comment by david-alex-cohen-zone** [comment]
On pourrait aussi garder le contenu reçu et juste jouer avec du css pour gérer les sauts de ligne : 
`white-space: pre-line;`
Qu'en pensez-vous ?

**Comment by paulcote** [comment]
Ouais ou quelque chose comme `.replace(/(?:\r\n|\r|\n)/g, '<br>');` dans le javascript. Je risque de faire ça de mon côté pour les autres outils qui se basent sur cette description là.

**Comment by jdecaron** [comment]
https://github.com/webaquebec/webaquebec2016-web/pull/75

**Comment by jdecaron** [comment]
TODO: faire le même fix dans les blogs.

**Comment by jdecaron** [comment]
Ajouter un element br pour chaque retour de chariot dans le blog ne donne pas un bon résultat, voir cette capture d'écran: http://i.imgur.com/q8xgFUv.png

**Comment by paulcote** [comment]
Je pense pas que ça soit nécessaire sur les articles de blogue vu que le contenu de l'article provient du WYSIWYG.

**Comment by jdecaron** [comment]
Je suis d'accord, l'éditeur de texte de Wordpress fait lui même sa transformation de formatage vers du HTML valide.
